<?php

namespace LazyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use LazyBundle\Entity\Traits\GeneratedIntegerIdentifiableTrait;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\MappedSuperclass()
 * @ORM\EntityListeners({"LazyBundle\EntityListener\FileEntityListener"})
 */
abstract class FileEntity implements IdentifiableEntityInterface {
    use GeneratedIntegerIdentifiableTrait;
    /**
     * Auto generated by entity listener
     * @ORM\Column(type="string", length=255)
     */
    protected $filename;

    /**
     * Auto generated by entity listener
     * @var string
     */
    protected $tempFilename;

    /**
     * @var File
     * @Assert\File()
     * @Assert\NotBlank()
     * @ORM\Column(type="string")
     */
    protected $file;

    /**
     * @var string
     */
    protected $webView;

    public function getId(): ?int {
        return $this->id;
    }

    public function getFilename(): ?string {
        return $this->filename;
    }

    public function setFilename(string $filename): self {
        $this->filename = $filename;
        return $this;
    }

    public function getFile(): ?File {
        return $this->file;
    }

    public function setFile(File $file = null): self {
        $this->file = $file;
        return $this;
    }

    public function getTempFilename(): ?string {
        return $this->tempFilename;
    }

    public function setTempFilename($filename): self {
        $this->tempFilename = $filename;
        return $this;
    }

    public function getWebView(): string {
        return $this->webView;
    }

    public function setWebView(string $webView): self {
        $this->webView = $webView;
        return $this;
    }
}