services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $fileUploaderTargetPath: '%kernel.project_dir%/var/upload'
            $fileEntityUploadPath: '%kernel.project_dir%/public/upload'
            $assetsHelper: '@assets.packages'

    LazyBundle\:
        resource: '../../{Component,Command,Controller,EntityListener,EventListener,Manager,Service}'

    # Event Listeners
    LazyBundle\EventListener\MappingListener:
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
            - { name: doctrine.event_listener, event: onSchemaColumnDefinition }
            - { name: doctrine.event_listener, event: postLoad, priority: 9999 }
        arguments: ['@LazyBundle\Manager\ManagerRegistry', ~]

    LazyBundle\EntityListener\EasyAdmin\FileEntityListener:
        tags:
            - { name: kernel.event_listener, event: easy_admin.pre_remove }
            - { name: kernel.event_listener, event: easy_admin.pre_update }
            - { name: kernel.event_listener, event: easy_admin.pre_persist }