services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $projectDir: '%kernel.project_dir%'
#            $assetsHelper: '@assets.packages'
    _instanceof:
        EasyCorp\Bundle\EasyAdminBundle\Form\Type\Configurator\TypeConfiguratorInterface:
            tags:
                - { name: 'easyadmin.form.type.configurator' }
        # Doctrine mapping events
        LazyBundle\EventListener\MappingListener:
            tags:
                - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
                - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }
                - { name: doctrine.event_listener, event: loadClassMetadata }
                #- { name: doctrine.event_listener, event: onSchemaColumnDefinition }
                - { name: doctrine.event_listener, event: postLoad, priority: 9999 }
                - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
                - { name: kernel.event_listener, event: console.terminate, method: onConsoleTerminate }

    LazyBundle\:
        resource: '../../{Component,Command,Controller,DataCollector, EntityListener,EventListener,Form,Manager,Service,Twig}'