services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $projectDir: '%kernel.project_dir%'
#            $assetsHelper: '@assets.packages'
            $cronConfig: '@=config("lazy", "cron")'
    _instanceof:
        EasyCorp\Bundle\EasyAdminBundle\Form\Type\Configurator\TypeConfiguratorInterface:
            tags:
                - { name: 'easyadmin.form.type.configurator' }
        # Doctrine mapping events
        LazyBundle\EventSubscriber\DoctrineMappingEventSubscriber:
            tags:
                - { name: doctrine.event_listener, event: loadClassMetadata }
                #- { name: doctrine.event_listener, event: onSchemaColumnDefinition }
                - { name: doctrine.event_listener, event: postLoad, priority: 9999 }

    LazyBundle\:
        resource: '../../{Component,Command,Controller,DataCollector,EntityListener,EventSubscriber,Factory,Form,Manager,Service,Twig}'

    LazyBundle\Factory\JobbyFactoryInterface:
        alias: 'LazyBundle\Factory\JobbyFactory'

    Jobby\Jobby:
        factory: ['@LazyBundle\Factory\JobbyFactoryInterface', 'generate']